export enum Phase {
  GAME_CREATION = 'GAME_CREATION',
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
  LOBBY_READY = 'LOBBY_READY',
  ROLE_DISTRIBUTION = 'ROLE_DISTRIBUTION',
  ROUND_DESCRIPTION = 'ROUND_DESCRIPTION',
  ROUND_DISCUSSION = 'ROUND_DISCUSSION',
  ROUND_VOTING = 'ROUND_VOTING',
  ROUND_RESULT = 'ROUND_RESULT',
  WHITE_TRANSITION = 'WHITE_TRANSITION',
  WIN_LOSE_CHECK = 'WIN_LOSE_CHECK',
  GAME_ENDED = 'GAME_ENDED',
}
